# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install fastify && npm install fastify-websocket && npm install @fastify/websocket && npm install -D nodemon && npm install fastify-swagger uuid && npm install -g wscat

# Copy the rest of the application code to the working directory
COPY . .


EXPOSE 5000

CMD [ "npm", "run", "dev" ]