-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- INSERT INTO users (name, age) VALUES ('John Doe', 30);
-- INSERT INTO users (name, age) VALUES ('Jane Smith', 25);`
-- INSERT INTO users (name, age) VALUES ('Alice Johnson', 28);
-- INSERT INTO users (name, age) VALUES ('Bob Brown', 35);
DROP TABLE users;
-- SELECT * FROM users;
-- SELECT * FROM users;
